server:
  port: 8001
spring:
  application:
    name: user-score-api

  jackson:
    default-property-inclusion: NON_NULL

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:user-score
    username: sa
    password:

  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  output:
    ansi:
      enabled: ALWAYS

app:
  name: ${spring.application.name}
  version: @project.version@

client:
  brasil-api-cep: https://brasilapi.com.br/api/cep/v2/

jwt:
  expires: 86400
  public-key: classpath:keys/public.pub
  private-key: classpath:keys/private.key

management:
  server:
    port: 8002

springdoc:
  swagger-ui:
    configUrl: /v3/api-docs/swagger-config
    url: /v3/api-docs
